### ISSUE TITLE
Possibility of using tornado.gen vs adisp?

### ISSUE THREAD

**Issue by whardier** [imvalgo/brukva#23]
tornado.gen and adisp.process don't mix well together.  Have there been any forks that prefer tornado.gen or is this a future goal for brukva?

**Comment by majek** [comment]
Take a look at this experiment: https://github.com/majek/rons

**Comment by whardier** [comment]
Yup Yup.  I ended up just writing my own simple socket client and then
moved off to using webdis :)

On Sat, Feb 18, 2012 at 2:57 PM, Marek Majkowski
reply@reply.github.com
wrote:

**Comment by davidwilemski** [comment]
I just found this: https://github.com/leporo/tornado-redis
